### ISSUE TITLE
Can't register for slack for cuke

### ISSUE THREAD

**Issue by Johnlon** [cucumber/common#2169] opened 2024-04-29 18:41 UTC
### 🤔 What's the problem you've observed?

When I type in my email on your registration page I get.   An error like..

API token expired

Is that app broken?

Thanks John

**Comment by mpkorstanje** [comment] 2024-04-29 21:39
Duplicate of #2168. As a work around you can use https://join.slack.com/t/cucumberbdd/shared_invite/zt-2i0fvyv35-PgrGAwIx3L~lFngzWkb86Q for now.

**Closed by mpkorstanje** 2024-04-29 21:39 UTC
Labels: :bank: debt
