### ISSUE TITLE
Add pretty-formatters for Gherkin (for Java)

### ISSUE THREAD

**Issue by jamietanna** [cucumber/common#1729] opened 2021-09-06 21:21 UTC
**Is your feature request related to a problem? Please describe.**

As someone who writes Gherkin feature files, I'd like to be sure my formatting is consistent across contributors to the project - whether editing in an IDE, or a text editor - and that can be automated as part of i.e. [a code formatter like Spotless](https://github.com/diffplug/spotless/issues/907)

**Describe the solution you'd like**

Add a pretty-formatter for Gherkin as a first-class citizen. This would allow taking i.e. a `String`, returning a `String` that is formatted according to pre-defined rules, and with indentation that can be specified.

I've recently implemented this in https://gitlab.com/jamietanna/gherkin-formatter and have licensed as MIT purposefully so Cucumber could take it as-is.

**Describe alternatives you've considered**

We write our own formatter.

**Comment by aslakhellesoy** [comment] 2021-09-06 21:50
Duplicate of #1662. Also see https://github.com/cucumber/common/pull/1725

**Closed by aslakhellesoy** 2021-09-06 21:50 UTC

**Comment by aslakhellesoy** [comment] 2021-09-06 21:59
But your code is really nice! Thanks for the effort :-)

**Comment by jamietanna** [comment] 2021-09-07 06:19
Thanks @aslakhellesoy - do you think it's worth me raising a separate PR for importing my implementation?

**Comment by laeubi** [comment] 2021-09-14 09:21
@jamietanna this could be really usefull especially for the cucumber-eclipse plugin that currently lacks formatting capabilities.
